//
//  Member.swift
//
//
//  Created by gulje on 22.06.2023.
//

import Foundation

public struct Member: Codable {
  /// Composite primary key consisting of server and user id
  public let id: MemberID

  /// ISO8601 formatted timestamp
  public let joinedAt: String

  /// Member's nickname
  public let nickname: String?

  /// Representation of a File on Revolt Generated by Autumn
  public let avatar: File?

  /// Member's roles
  public let roles: [String]?

  /// ISO8601 formatted timestamp
  public let timeout: String?

  private enum CodingKeys: String, CodingKey {
    case id = "_id"
    case joinedAt = "joined_at"
    case nickname
    case avatar
    case roles
    case timeout
  }
}

public struct MemberID: Codable {
  public let server: String

  public let user: String
}
